In [4]:
import pandas as pd
import yfinance as yfinance
import warnings
warnings.filterwarnings('ignore')

In [5]:
url = "https://archives.nseindia.com/content/equities/EQUITY_L.csv"
nse_stocks=pd.read_csv(url)

In [6]:
print(f"Total number of nse_stocks = {len(nse_stocks)}")

Total number of nse_stocks = 2251

In [10]:
nse_stocks.head(10)

,SYMBOL,NAME OF COMPANY,SERIES,DATE OF LISTING,PAID UP VALUE,MARKET LOT,ISIN NUMBER,FACE VALUE
0,20MICRONS,20 Microns Limited,EQ,06-OCT-2008,5,1,INE144J01027,5
1,21STCENMGM,21st Century Management Services Limited,EQ,03-MAY-1995,10,1,INE253B01015,10
2,360ONE,360 ONE WAM LIMITED,EQ,19-SEP-2019,1,1,INE466L01038,1
3,3IINFOLTD,3i Infotech Limited,EQ,22-OCT-2021,10,1,INE748C01038,10
4,3MINDIA,3M India Limited,EQ,13-AUG-2004,10,1,INE470A01017,10
5,3PLAND,3P Land Holdings Limited,EQ,19-JUL-1995,2,1,INE105C01023,2
6,5PAISA,5Paisa Capital Limited,EQ,16-NOV-2017,10,1,INE618L01018,10
7,63MOONS,63 moons technologies limited,EQ,20-JUN-2005,2,1,INE111B01023,2
8,A2ZINFRA,A2Z Infra Engineering Limited,BE,23-DEC-2010,10,1,INE619I01012,10
9,AAATECH,AAA Technologies Limited,EQ,28-NOV-2022,10,1,INE0D0U01013,10

In [16]:
url_bse="../data/bse_stocks.csv"
bse_stocks=pd.read_csv(url_bse)

In [17]:
print(f"number of stocks in bse = {len(bse_stocks)}")

number of stocks in bse = 4851

In [14]:
bse_stocks.head(10)

,,,,,Security Code,Issuer Name,Security Id,Security Name,Status,Group,Face Value,ISIN No,Instrument
500002,ABB India Limited,ABB,ABB India Ltd,Active,A,2.0,INE117A01022,Equity,NaN,NaN,NaN,NaN,NaN
500003,Aegis Logistics Ltd.,AEGISLOG,Aegis Logistics Ltd,Active,A,1.0,INE208C01025,Equity,NaN,NaN,NaN,NaN,NaN
500008,Amara Raja Energy & Mobility Limited,ARE&M,Amara Raja Energy & Mobility Ltd,Active,A,1.0,INE885A01032,Equity,NaN,NaN,NaN,NaN,NaN
500009,Ambalal Sarabhai Enterprise Ltd.,AMBALALSA,Ambalal Sarabhai Enterprises Ltd,Active,X,10.0,INE432A01017,Equity,NaN,NaN,NaN,NaN,NaN
500012,Andhra Petrochemicals Ltd.,ANDHRAPET,Andhra Petrochemicals Ltd,Active,X,10.0,INE714B01016,Equity,NaN,NaN,NaN,NaN,NaN
500013,Ansal Properties & Infrastructure Ltd.,ANSALAPI,Ansal Properties & Infrastructure Ltd,Active,Z,5.0,INE436A01026,Equity,NaN,NaN,NaN,NaN,NaN
500014,UTIQUE ENTERPRISES LIMITED,UTIQUE,Utique Enterprises Ltd,Active,X,10.0,INE096A01010,Equity,NaN,NaN,NaN,NaN,NaN
500016,Aruna Hotels Ltd.,ARUNAHTEL,Aruna Hotels Ltd,Active,X,10.0,INE957C01019,Equity,NaN,NaN,NaN,NaN,NaN
500020,Bombay Dyeing & Mfg. Co. Ltd.,BOMDYEING,Bombay Dyeing & Manufacturing Company Ltd,Active,A,2.0,INE032A01023,Equity,NaN,NaN,NaN,NaN,NaN
500023,Asian Hotels (North) Limited,ASIANHOTNR,Asian Hotels (North) Ltd,Active,B,10.0,INE363A01022,Equity,NaN,NaN,NaN,NaN,NaN

In [15]:
nse_stocks.to_csv("../data/nse_stocks.csv", index='False')

In [18]:
print(f"Total NSE stocks: {len(nse_stocks)}")
print("Saved to data folder successfully!")
print("\nColumns available:")

Total NSE stocks: 2251
Saved to data folder successfully!

Columns available:

In [19]:
print(nse_stocks.columns.tolist())

['SYMBOL', 'NAME OF COMPANY', ' SERIES', ' DATE OF LISTING', ' PAID UP VALUE', ' MARKET LOT', ' ISIN NUMBER', ' FACE VALUE']

In [22]:
nse_stocks.columns.to_list()

['SYMBOL',
 'NAME OF COMPANY',
 ' SERIES',
 ' DATE OF LISTING',
 ' PAID UP VALUE',
 ' MARKET LOT',
 ' ISIN NUMBER',
 ' FACE VALUE']

In [23]:
# Add exchange column to identify source
nse_stocks['Exchange'] = 'NSE'
bse_stocks['Exchange'] = 'BSE'

In [24]:
nse_stocks

,SYMBOL,NAME OF COMPANY,SERIES,DATE OF LISTING,PAID UP VALUE,MARKET LOT,ISIN NUMBER,FACE VALUE,Exchange
0,20MICRONS,20 Microns Limited,EQ,06-OCT-2008,5,1,INE144J01027,5,NSE
1,21STCENMGM,21st Century Management Services Limited,EQ,03-MAY-1995,10,1,INE253B01015,10,NSE
2,360ONE,360 ONE WAM LIMITED,EQ,19-SEP-2019,1,1,INE466L01038,1,NSE
3,3IINFOLTD,3i Infotech Limited,EQ,22-OCT-2021,10,1,INE748C01038,10,NSE
4,3MINDIA,3M India Limited,EQ,13-AUG-2004,10,1,INE470A01017,10,NSE
...,...,...,...,...,...,...,...,...,...
2246,ZOTA,Zota Health Care LImited,EQ,19-AUG-2019,10,1,INE358U01012,10,NSE
2247,ZUARI,Zuari Agro Chemicals Limited,EQ,27-NOV-2012,10,1,INE840M01016,10,NSE
2248,ZUARIIND,ZUARI INDUSTRIES LIMITED,EQ,12-APR-1995,10,1,INE217A01012,10,NSE
2249,ZYDUSLIFE,Zydus Lifesciences Limited,EQ,18-APR-2000,1,1,INE010B01027,1,NSE
2250,ZYDUSWELL,Zydus Wellness Limited,EQ,13-NOV-2009,2,1,INE768C01028,2,NSE

In [25]:
nse_clean=nse_stocks[['SYMBOL', 'NAME OF COMPANY', 'Exchange']].copy()
nse_clean.columns=['Symbol', 'Company Name', 'Exchange']

In [26]:
nse_clean

          Symbol                              Company Name Exchange
0      20MICRONS                        20 Microns Limited      NSE
1     21STCENMGM  21st Century Management Services Limited      NSE
2         360ONE                       360 ONE WAM LIMITED      NSE
3      3IINFOLTD                       3i Infotech Limited      NSE
4        3MINDIA                          3M India Limited      NSE
...          ...                                       ...      ...
2246        ZOTA                  Zota Health Care LImited      NSE
2247       ZUARI              Zuari Agro Chemicals Limited      NSE
2248    ZUARIIND                  ZUARI INDUSTRIES LIMITED      NSE
2249   ZYDUSLIFE                Zydus Lifesciences Limited      NSE
2250   ZYDUSWELL                    Zydus Wellness Limited      NSE

[2251 rows x 3 columns]

In [47]:
bse_stocks = pd.read_csv("../data/bse_stocks.csv", index_col=False)

In [48]:
bse_stocks

,Security Code,Issuer Name,Security Id,Security Name,Status,Group,Face Value,ISIN No,Instrument
0,500002,ABB India Limited,ABB,ABB India Ltd,Active,A,2.0,INE117A01022,Equity
1,500003,Aegis Logistics Ltd.,AEGISLOG,Aegis Logistics Ltd,Active,A,1.0,INE208C01025,Equity
2,500008,Amara Raja Energy & Mobility Limited,ARE&M,Amara Raja Energy & Mobility Ltd,Active,A,1.0,INE885A01032,Equity
3,500009,Ambalal Sarabhai Enterprise Ltd.,AMBALALSA,Ambalal Sarabhai Enterprises Ltd,Active,X,10.0,INE432A01017,Equity
4,500012,Andhra Petrochemicals Ltd.,ANDHRAPET,Andhra Petrochemicals Ltd,Active,X,10.0,INE714B01016,Equity
...,...,...,...,...,...,...,...,...,...
4846,890228,Allcargo Terminals Limited,ATLPP,Allcargo Terminals Ltd,Active,B,2.0,IN90NN701011,Equity
4847,890230,Ace Software Exports ltd.,ACESEPP,Ace Software Exports ltd,Active,X,10.0,IN9849B01026,Equity
4848,890231,ANIRIT VENTURES LIMITED,ANIRITPP,ANIRIT VENTURES Ltd,Active,XT,10.0,IN9161F01019,Equity
4849,890232,KRISHIVAL FOODS LIMITED,KRISHPP,KRISHIVAL FOODS Ltd,Active,B,10.0,IN90GGO01013,Equity
4850,890233,PVV Infra Limited,PVVIPP,PVV Infra Ltd,Active,X,5.0,IN9428B01029,Equity

In [49]:
bse_stocks['Exchange'] = 'BSE'

In [50]:
bse_clean = bse_stocks[['Security Id', 'Issuer Name', 'Exchange']].copy()
bse_clean.columns = ['Symbol', 'Company Name', 'Exchange']

print(f"BSE stocks: {len(bse_clean)}")
print(bse_clean.head(5))

BSE stocks: 4851
      Symbol                          Company Name Exchange
0        ABB                     ABB India Limited      BSE
1   AEGISLOG                  Aegis Logistics Ltd.      BSE
2      ARE&M  Amara Raja Energy & Mobility Limited      BSE
3  AMBALALSA      Ambalal Sarabhai Enterprise Ltd.      BSE
4  ANDHRAPET            Andhra Petrochemicals Ltd.      BSE

In [51]:
# Combine both
master_list = pd.concat([nse_clean, bse_clean], ignore_index=True)
master_list

          Symbol                              Company Name Exchange
0      20MICRONS                        20 Microns Limited      NSE
1     21STCENMGM  21st Century Management Services Limited      NSE
2         360ONE                       360 ONE WAM LIMITED      NSE
3      3IINFOLTD                       3i Infotech Limited      NSE
4        3MINDIA                          3M India Limited      NSE
...          ...                                       ...      ...
7097       ATLPP                Allcargo Terminals Limited      BSE
7098     ACESEPP                 Ace Software Exports ltd.      BSE
7099    ANIRITPP                   ANIRIT VENTURES LIMITED      BSE
7100     KRISHPP                   KRISHIVAL FOODS LIMITED      BSE
7101      PVVIPP                         PVV Infra Limited      BSE

[7102 rows x 3 columns]

In [52]:
# Save to data folder
master_list.to_csv("../data/master_stocks.csv", index=False)

print(f"NSE stocks:     {len(nse_clean)}")
print(f"BSE stocks:     {len(bse_clean)}")
print(f"Total universe: {len(master_list)}")
master_list.head(5)

NSE stocks:     2251
BSE stocks:     4851
Total universe: 7102

       Symbol                              Company Name Exchange
0   20MICRONS                        20 Microns Limited      NSE
1  21STCENMGM  21st Century Management Services Limited      NSE
2      360ONE                       360 ONE WAM LIMITED      NSE
3   3IINFOLTD                       3i Infotech Limited      NSE
4     3MINDIA                          3M India Limited      NSE